src/main/scala/com/codacy/analysis/cli/formatter/Formatter.scala

Avoid appending cli output to already existing file, replacing it instead.

Avoid appending cli output to already existing file, replacing it instead

---

bin/codacy-analysis-cli.sh
src/main/scala/com/codacy/analysis/cli/Main.scala
src/main/scala/com/codacy/analysis/cli/analysis/CodacyPluginsAnalyser.scala
src/main/scala/com/codacy/analysis/cli/command/CLIApp.scala
src/main/scala/com/codacy/analysis/cli/command/analyse/AnalyseExecutor.scala
src/main/scala/com/codacy/analysis/cli/tools/Tool.scala
src/main/scala/com/codacy/analysis/cli/upload/ResultsUploader.scala
src/test/scala/com/codacy/analysis/cli/CodacyClientSpec.scala

* Added `*Value` for variables with "boolean" types
* Improved file permission overrides
* Added better logs to end of upload and analysis

Improve end of analysis logs

---

README.md
src/main/scala/com/codacy/analysis/cli/Main.scala
src/main/scala/com/codacy/analysis/cli/analysis/CodacyPluginsAnalyser.scala
src/main/scala/com/codacy/analysis/cli/command/CLIApp.scala
src/main/scala/com/codacy/analysis/cli/command/analyse/AnalyseExecutor.scala
src/main/scala/com/codacy/analysis/cli/tools/Tool.scala
src/test/scala/com/codacy/analysis/cli/AnalyseExecutorSpec.scala
src/test/scala/com/codacy/analysis/cli/files/FileSystemFileCollectorSpec.scala
src/test/scala/com/codacy/analysis/cli/tools/ToolSpec.scala

* Added new parameter to the CLI to run tools that may need network access to execute. If the parameter is not provided, these tools are not considered to run the analysis.
* Added unit tests.
* Updated README.

Added 'allow-network' parameter to the CLI to run tools that may need network access to execute

---

.circleci/config.yml
README.md
scripts/publish_docker.sh
scripts/publish_lib.sh

* Fix script name on circleci config file for lib's publish to sonatype.
* Updated readme

Fix publish to sonatype on circle ci

---

README.md
build.sbt

This setting was supposed to avoid the pom being created only when the docker is published, but it's avoiding it always...
Also added the maven badge to the project.

Remove setting that avoids the pom being written.

---

cli/src/main/scala/com/codacy/analysis/cli/command/analyse/AnalyseExecutor.scala
core/src/main/scala/com/codacy/analysis/core/tools/DuplicationTool.scala
core/src/main/scala/com/codacy/analysis/core/tools/Tool.scala
core/src/main/scala/com/codacy/analysis/core/utils/LanguagesHelper.scala
core/src/test/scala/com.codacy.analysis.core/tools/DuplicationToolSpec.scala
core/src/test/scala/com.codacy.analysis.core/utils/LanguagesHelperSpec.scala

* Refactor the logic for the tool and language detection from the fileTargets.
* Add unit tests
* Add logs

Refactored the logic for the tool and language detection from the fileTargets

---

scripts/compile.sh
scripts/lint.sh

Scripts improvement

---

cli/src/main/scala/com/codacy/analysis/cli/command/analyse/AnalyseExecutor.scala
cli/src/main/scala/com/codacy/analysis/cli/command/analyse/MetricsToolExecutor.scala
cli/src/test/scala/com/codacy/analysis/cli/command/analyse/MetricsToolExecutorSpec.scala

This still needs some discussion about where should I put the logic to aggregate the file metrics.

Aggregate fileMetrics for the same files

---

cli/src/main/scala/com/codacy/analysis/cli/command/analyse/AnalyseExecutor.scala

Currently, there are ignored files included in the list of analysed files that is being sent to the backend (for instance, .png files). This fix is to avoid it.

Fix to avoid sending to the backend ignored files 

---

core/src/main/scala/com/codacy/analysis/core/git/Repository.scala
core/src/test/scala/com.codacy.analysis.core/git/RepositorySpec.scala

Removed call on jGit for untracked folders 
Added tests

Fix untracked directories

---

cli/src/main/scala/com/codacy/analysis/cli/Main.scala
cli/src/test/scala/com/codacy/analysis/cli/CLISpec.scala
project/Dependencies.scala

Added cleanup of config files before and after analysis
Added tests for cleanup

Fix configs cleanup

---

README.md
cli/src/main/scala/com/codacy/analysis/cli/formatter/Text.scala

Improve metrics and duplication output ft 5862

---

README.md
cli/src/main/scala/com/codacy/analysis/cli/analysis/ExitStatus.scala

Fixes problems in exit codes to help #126

Fix exit codes

---

project/Dependencies.scala

updated codacy-plugins to add Crystal

---

project/Dependencies.scala

Bumping version of codacy-plugins -> codacy-plugins-api.

fix: Add support for SQL file parsing FT-6941

---

.circleci/config.yml
scripts/checkout.sh

- Fix linting errors in checkout.sh

fix: Fix typo in CI

---

.circleci/config.yml
README.md

fix: Add codacy/tag-version to circleci build

---

cli/src/main/scala/com/codacy/analysis/cli/analysis/AnalyseExecutor.scala
cli/src/main/scala/com/codacy/analysis/cli/command/CLIApp.scala
cli/src/test/scala/com/codacy/analysis/cli/AnalyseExecutorToolsSpec.scala
core/src/main/scala/com/codacy/analysis/core/analysis/CodacyPluginsAnalyser.scala
core/src/main/scala/com/codacy/analysis/core/tools/Tool.scala
core/src/test/scala/com.codacy.analysis.core/files/FileCollectorSpec.scala
project/Dependencies.scala
scripts/compile.sh
scripts/lint.sh
scripts/test.sh

- Run Spotbugs even without --allow-network option

bump: Bump codacy-plugins to 15.1.0

---

cli/src/main/scala/com/codacy/analysis/cli/formatter/Sarif.scala
cli/src/test/scala/com/codacy/analysis/cli/formatter/SarifSpec.scala

These issues are reported at a different priority level than what Codacy
originally reported.

feature: Add SARIF support for non-security issues [CY-2844]

---

README.md
cli/src/main/scala/com/codacy/analysis/cli/command/AnalyseCommand.scala
cli/src/main/scala/com/codacy/analysis/cli/command/CLIApp.scala
cli/src/main/scala/com/codacy/analysis/cli/configuration/CLIConfiguration.scala
cli/src/main/scala/com/codacy/analysis/cli/formatter/Formatter.scala
cli/src/main/scala/com/codacy/analysis/cli/formatter/Json.scala
cli/src/main/scala/com/codacy/analysis/cli/formatter/Sarif.scala
cli/src/main/scala/com/codacy/analysis/cli/formatter/Text.scala
cli/src/test/scala/com/codacy/analysis/cli/AnalyseExecutorSpec.scala
cli/src/test/scala/com/codacy/analysis/cli/configuration/CLIConfigurationSpec.scala
cli/src/test/scala/com/codacy/analysis/cli/formatter/SarifSpec.scala

…de scanning compatibility [CY-2844]
[CY-2844]: https://codacy.atlassian.net/browse/CY-2844

feature: Add a flag to adapt SARIF ouput issue severity for GitHub code scanning compatibility [CY-2844]

---

cli/src/main/scala/com/codacy/analysis/cli/analysis/AnalyseExecutor.scala
cli/src/main/scala/com/codacy/analysis/cli/command/AnalyseCommand.scala
cli/src/main/scala/com/codacy/analysis/cli/formatter/Formatter.scala
cli/src/main/scala/com/codacy/analysis/cli/formatter/Json.scala
cli/src/main/scala/com/codacy/analysis/cli/formatter/Sarif.scala
cli/src/main/scala/com/codacy/analysis/cli/formatter/Text.scala
cli/src/test/scala/com/codacy/analysis/cli/analysis/ExitStatusSpec.scala
cli/src/test/scala/com/codacy/analysis/cli/formatter/SarifSpec.scala

Sarif downgrades severity level for non-security issues.
But the CLI was not detecting security patternts the correct way.
This commit should fix that

fix: Fix severity level in Sarif CY-3724

---

README.md
cli/src/main/scala/com/codacy/analysis/cli/command/AnalyseCommand.scala
cli/src/main/scala/com/codacy/analysis/cli/command/CLIApp.scala
cli/src/test/scala/com/codacy/analysis/cli/CLISpec.scala

Add flag to skip commit UUID validation

---

.circleci/config.yml

- Remove install_sbt_version parameters

fix: Downgrade orb to 5.2.3

---

README.md

Applies the same improvement as in https://github.com/codacy/codacy-analysis-cli-action/pull/73.

doc: Improve description for upload-batch-size

---

.circleci/config.yml
Dockerfile
README.md
build.sbt
cli/src/test/scala/com/codacy/analysis/cli/AnalyseExecutorSpec.scala
cli/src/test/scala/com/codacy/analysis/cli/CLISpec.scala
core/src/test/scala/com.codacy.analysis.core/files/FileCollectorSpec.scala
core/src/test/scala/com.codacy.analysis.core/tools/DuplicationToolSpec.scala
core/src/test/scala/com.codacy.analysis.core/tools/MetricsToolSpec.scala
project/Common.scala

- Commit Dockerfile instead of using `docker:publishLocal`

bump: Bump docker image to work with arm64/v8

---

.circleci/config.yml

Just a try, as we have the following error:

fix: Add new cache prefix

---

README.md

Fix LTS -> TLS typo in README.md

---

README.md

Updates the repo README file with suggestions from Marketing.
For more context, see [Slack thread](https://codacy.slack.com/archives/C011BCR2RN3/p1699870518527649) and [Slite page](https://codacy.slite.com/app/docs/MvDrtzmzg3PVr7/Github-pages-updates).

doc: README updates

---

.circleci/config.yml

Adapt test jobs for new RP instance.
Related to [REL-1421](https://codacy.atlassian.net/browse/REL-1421)
[REL-1421]: https://codacy.atlassian.net/browse/REL-1421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: Migrate RP

---

project/Dependencies.scala

[REL-1459](https://codacy.atlassian.net/browse/REL-1459)
[REL-1459]: https://codacy.atlassian.net/browse/REL-1459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Use scalaj fork

---

README.md
cli/src/main/scala/com/codacy/analysis/cli/analysis/AnalyseExecutor.scala
cli/src/main/scala/com/codacy/analysis/cli/analysis/ToolSelector.scala
cli/src/main/scala/com/codacy/analysis/cli/command/CLIApp.scala
cli/src/main/scala/com/codacy/analysis/cli/configuration/CLIConfiguration.scala
cli/src/test/scala/com/codacy/analysis/cli/ToolSelectorSpec.scala
cli/src/test/scala/com/codacy/analysis/cli/configuration/CLIConfigurationSpec.scala
core/src/main/scala/com/codacy/analysis/core/tools/Tool.scala
core/src/test/scala/com.codacy.analysis.core/files/FileCollectorSpec.scala

feat: [TCE-1039] Add parameter 'registryAddress' in order to support alternative registry addresses
