codacy/codacy-analysis-cli

build.sbt

Had to move the credentials for sonatype to the "root" on the sbt to avoid the o avoid the error "java.lang.IllegalStateException: No credential is found for oss.sonatype.org. Prepare ~/.sbt/(sbt_version)/sonatype.sbt file." on circleci. 
I already tested this modification directly on circleci and it worked.

Moved Sonatype credentials to root 

---

.circleci/config.yml

Make sure we cannot publish a stable version without the tests passing

Update job dependencies

---

README.md
bin/codacy-analysis-cli.sh

Depends on https://github.com/codacy/codacy-analysis-cli/pull/44

Use stable as default distribution version

---

build.sbt
project/Common.scala

the dependencies weren't being resolved since they were changed to the core subproject.

Adds inThisBuild to the resolvers 

---

cli/src/main/scala/com/codacy/analysis/cli/Main.scala
core/src/main/scala/com/codacy/analysis/core/model/ResultsSet.scala
core/src/test/scala/com.codacy.analysis.core/upload/ResultsUploaderSpec.scala

It is needed to be able to check for missing files on the back end

Adds set of analysed files to DuplicationAnalysis.Success

---

.circleci/config.yml

We were using a key only present in the qa-automation project instead of the general one

Use global CircleCI key for Bitbucket

---

core/src/main/scala/com/codacy/analysis/core/tools/DuplicationTool.scala
core/src/main/scala/com/codacy/analysis/core/tools/MetricsTool.scala
core/src/main/scala/com/codacy/analysis/core/tools/Tool.scala
project/Dependencies.scala

It now reads codacy.tests.noremove as a property to keep the containers for debug

feature: Depend on the new codacy-plugins

---

core/src/main/scala/com/codacy/analysis/core/clients/CodacyClient.scala

The problem is nginx, used in k8s, by default drops all http request headers that contain the underscore char, meaning that project_token and api_token headers are not reaching the route handlers and these are failing on the authentication step.
Therefore we are changing the API tokens to use "-" instead of "_".
More context in bitbucket.org/qamine/codacy-website/pull-requests/3185

Replace tokens underscore with hyphen: CY-1262

---

README.md

The location of api tokens is now in a tab called Access Management

docs: update name of api tokens tab

---

.circleci/config.yml

We missed a lot of tests failing and with this change we hope it's easier to find failing workflows

test: Add slack notification to integration tests

---

README.md
bin/codacy-analysis-cli.sh
build.sbt
cli/src/main/scala/com/codacy/analysis/cli/Main.scala
cli/src/main/scala/com/codacy/analysis/cli/command/AnalyseCommand.scala
cli/src/main/scala/com/codacy/analysis/cli/command/CLIApp.scala
cli/src/main/scala/com/codacy/analysis/cli/configuration/CLIConfiguration.scala
cli/src/test/scala/com/codacy/analysis/cli/AnalyseExecutorSpec.scala
cli/src/test/scala/com/codacy/analysis/cli/CLISpec.scala
cli/src/test/scala/com/codacy/analysis/cli/configuration/CLIConfigurationSpec.scala
core/src/main/scala/com/codacy/analysis/core/tools/Tool.scala
core/src/test/scala/com.codacy.analysis.core/tools/DuplicationToolSpec.scala
core/src/test/scala/com.codacy.analysis.core/tools/MetricsToolSpec.scala
core/src/test/scala/com.codacy.analysis.core/upload/ResultsUploaderSpec.scala

This change guarantees retro-compatibility with the `analyse` command.

breaking: Change spelling of the `analyse` command to `analyze` [CY-2939]

---

cli/src/main/scala/com/codacy/analysis/cli/command/AnalyseCommand.scala
toolRepository-plugins/src/main/scala/com/codacy/toolRepository/plugins/ToolRepositoryPlugins.scala

If a URL is used with a trailing dash,
the CLI will fail because it cannot fetch the tools' information.
This commit will fix that.

fix: Fixed bug caused by trailing dash in URL

---

README.md
cli/src/main/scala/com/codacy/analysis/cli/command/CLIApp.scala

This pull request removes references to the Account API Token from the documentation and CLI help output, since using the Account API Token only works for repositories belonging to legacy organizations and not for synced organizations.
These changes are similar to the ones on the Codacy Coverage Reporter: https://github.com/codacy/codacy-coverage-reporter/pull/256
See [CY-3474](https://codacy.atlassian.net/browse/CY-3474) for more details.

fix: Remove references to Account API Token CY-3474

---

.circleci/config.yml

Prevents noobs like me from doing the wrong thing

clean: Don't push 'stable' docker image for pull requests

---

README.md

- Add links to the existing documentation on how to generate project and account API tokens to help keep the information centralized.
- Add explicit recommendation to store the tokens in environment variables.

doc: Improve information about API tokens

---

README.md

Specifying the default value of `--max-tool-memory` using gigabytes (or even megabytes) makes the value easier to read and understand if it needs to be changed

doc: Change unit of --max-tool-memory default value to GB

---

README.md
core/src/main/scala/com/codacy/analysis/core/utils/SetOps.scala
core/src/test/scala/com.codacy.analysis.core/utils/SetOpsSpec.scala

fix: Make `--parallel` run effectively in parallel CY-4739 :breaking:

---

.circleci/config.yml

The latest orb fixes a regression issues on the publish docker step, which led to the need to downgrade the orb version in this workflow.

fix: Use latest orb

---

cli/src/main/scala/com/codacy/analysis/cli/command/CLIApp.scala

This occurrence of the help string wasn't updated in @heliocodacy's original pull request (https://github.com/codacy/codacy-analysis-cli/pull/413).

doc: Update help string for --skip-ssl-verification

---

README.md
cli/src/main/scala/com/codacy/analysis/cli/command/AnalyseCommand.scala
cli/src/main/scala/com/codacy/analysis/cli/command/CLIApp.scala
cli/src/main/scala/com/codacy/analysis/cli/configuration/CLIConfiguration.scala
cli/src/test/scala/com/codacy/analysis/cli/configuration/CLIConfigurationSpec.scala
core/src/main/scala/com/codacy/analysis/core/upload/ResultsUploader.scala
core/src/test/scala/com.codacy.analysis.core/upload/ResultsUploaderSpec.scala

This leaves current behaviour untouched (upload single batch of results), while adding the flag `--upload-batch-size`:
- if unset does default behaviour (50k results batches)
- if set, the value should be the number of results to upload per batch

feature: add upload batch size flag CY-5727

---

README.md
cli/src/main/scala/com/codacy/analysis/cli/analysis/ToolSelector.scala
core/src/main/scala/com/codacy/analysis/core/utils/HttpHelper.scala

Adds capability to run only issues analysis.
I was already possible for duplication and metrics, just extending it to fit the use case of some customers (and to mitigate our limitation of payload size for duplication and metrics)

feature: support issues-only analysis and log upload parsing failures CY-5727

---

cli/src/main/scala/com/codacy/analysis/cli/analysis/AnalyseExecutor.scala
cli/src/main/scala/com/codacy/analysis/cli/analysis/ToolSelector.scala
core/src/main/scala/com/codacy/analysis/core/analysis/Analyser.scala
core/src/main/scala/com/codacy/analysis/core/analysis/CodacyPluginsAnalyser.scala
core/src/main/scala/com/codacy/analysis/core/files/FileCollector.scala
core/src/main/scala/com/codacy/analysis/core/tools/MetricsTool.scala
core/src/test/scala/com.codacy.analysis.core/tools/MetricsToolSpec.scala
project/build.properties

We shouldn't be calling metrics tool to run for a set of empty files.
The normal linters seem already protected. I've put the change in the most similar place mirroring what the linters also do.

Fix request metrics analysis on empty files (IO-47)

---

README.md

Improves the description for the new flag `--skip-docker-test` introduced in #462 to let users know what it does since the previous description mentioned the name of our internal function instead.

doc: Improve description of --skip-docker-test TS-106

---

README.md

Adding instructions to use Codacy CLI when using Mac computers with Apple Silicon.

add docker mac silicon instructions

---

Dockerfile

The [issue](https://app.codacy.com/organizations/gh/codacy/security/findings/codacy-analysis-cli/944c0973-e3c7-40b8-bbaa-943f448545ee?priority=Critical%2C+High&status=Overdue) at hand. The `adduser` command creates a group for a new user, with the same name.

update dockerfile to fix codacy issue
